2023-06-19 18:37:12 | [ERROR] | (request.py).|getQueryShop(62) | HTTPConnectionPool(host='192.168.252.250', port=80): Max retries exceeded with url: /unf_vz_copy/hs/GetChangeShop/V1/GetShop (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa43b0d1570>, 'Connection to 192.168.252.250 timed out. (connect timeout=None)'))
2023-06-19 18:37:12 | [INFO] | (main.py).|main(107) | Change in stores - None
2023-06-19 18:38:01 | [INFO] | (main.py).|main(54) | Start programs
2023-06-19 18:38:01 | [INFO] | (main.py).|main(55) | Current path /home/administrator
2023-06-19 18:38:01 | [INFO] | (db.py).|__init__(56) | Connect DB
2023-06-19 18:38:01 | [INFO] | (db.py).|__init__(59) | Start create DB
2023-06-19 18:38:01 | [INFO] | (db.py).|__init__(71) | Connect to MySql DB
2023-06-19 18:38:01 | [INFO] | (main.py).|main(73) | Number of open cash shifts - 0
2023-06-19 18:38:01 | [INFO] | (dbMysql.py).|get_last_workshift(42) | Date of the last closed cash shift - 383
2023-06-19 18:38:01 | [INFO] | (dbMysql.py).|get_last_workshift(65) | Getting data on the last closed cash shifts
2023-06-19 18:38:01 | [INFO] | (main.py).|main(88) | Number of closed cash shifts - 0
2023-06-19 18:38:01 | [WARNING] | (main.py).|main(89) | l_workshift - ()
2023-06-19 18:40:12 | [ERROR] | (request.py).|getQueryShop(62) | HTTPConnectionPool(host='192.168.252.250', port=80): Max retries exceeded with url: /unf_vz_copy/hs/GetChangeShop/V1/GetShop (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f0c853d5570>, 'Connection to 192.168.252.250 timed out. (connect timeout=None)'))
2023-06-19 18:40:12 | [INFO] | (main.py).|main(107) | Change in stores - None
